In [177]:
import numpy as np

In [179]:
#1 -- The odd ones
#You’ve come across a dataset of star magnitudes (brightnesses) from various stellar clusters. 
#For your interstellar research, you only care about clusters where every star's magnitude is odd.
#Given a 2D array, write a function to find the rows where ALL values are odd numbers.

def odd_ones(dataset):
    odd_ones = []
    for row in dataset:
        if all(items % 2 != 0 for items in row): 
            odd_ones.append(row)
    return (odd_ones)
arr = np.array([[1, 2, 3], [5, 7, 9], [2, 4, 6], [7, 7, 7]])
odd_ones(arr)

[array([5, 7, 9]), array([7, 7, 7])]

In [181]:
#2 -- Let’s play Checkers!
#You’ve decided to take a break from your cutting-edge research and play checkers with your friends.
#Unfortunately, there is no checkerboard in sight! Therefore you must create one yourself

#2.1 Start by writing a function that creates a 8x8 square matrix with only zeros.
def checkerboard():
    return np.zeros((8, 8), dtype=int)  
    
checkerboard()

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [183]:
#2.2--For only the odd rows, make an alternating pattern of ones and zeros
def checkerboard_odd():
    odd_rows = np.zeros((8,8), dtype=int)
    odd_rows[::2, ::2] = 1
    return odd_rows
    
checkerboard_odd()

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [185]:
#2.3 -- Finish the checkerboard with the even rows.
def checkerboard_all():
    all_rows = np.zeros((8,8), dtype=int)
    all_rows[::2, ::2] = 1
    all_rows[1::2, 1::2] = 1
    return all_rows
    
checkerboard_all()

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [187]:
#2.4--Re-write your function such that the checkerboard begins with a 0 instead.
def checkerboard_zero():
    all_rows = np.zeros((8,8), dtype=int)
    all_rows[1::2, ::2] = 1
    all_rows[0::2, 1::2] = 1
    return all_rows
    
checkerboard_zero()


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [381]:
#3--The Expanding Universe
#You have now become fascinated with how dark energy is making galaxies accelerate away from us. 
#Write a function that takes in a string and a number,
#and returns the string with the specified number of spaces inserted between each letter, simulating the expansion of space!
def expansion(string, space_number):
    space_str = ''
    for i in string:
        space_str += (' ' * space_number).join(i)
        space_str += ' ' * space_number
    return space_str 
universe = np.array(['galaxy','clusters']) 
expansion(universe, 7)
    

'g       a       l       a       x       y       c       l       u       s       t       e       r       s       '

In [195]:
#4 -- While studying exoplanets, you decide to identify only the second-largest planet in each system. 
#Write a function that takes a 2D numpy array and returns an array containing only the second-largest value in each column (system)
def SecondLargest(planets):
    sort_numbers = np.sort(planets, axis=0) [::-1]
    second_largest = sort_numbers[1]
    return second_largest

np.random.seed(42)
planets = np.random.randint(100, 1000, (5, 5))
SecondLargest(planets)



array([566, 535, 960, 714, 230])